global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Configuration;
global using Autofac;
global using System.Reflection;
global using TranqService.Common.Extensions;
global using TranqService.Common.Attributes;
global using static TranqService.Common.Attributes.DependencyScopeAttribute;
global using System.Globalization;
global using System.Text.RegularExpressions;
global using System.Text.Json;
global using TranqService.Common.DataAccess;
global using TranqService.Common.Models.Configs;
global using static TranqService.Common.Data.Enums;
global using TranqService.Common.Abstract;
global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.Linq.Expressions;
global using TranqService.Common.Data;