global using Xunit;
global using Autofac.Extras.Moq;
global using TranqService.Ytdlp.DataAccess;
global using Autofac;
global using Microsoft.Extensions.Configuration;
global using TranqService.Common;
global using TranqService.Database;
global using TranqService.Shared;
global using TranqService.Ytdlp;