global using Serilog;
global using System.Text.Json.Nodes;
global using TranqService.Common.Data;
global using Autofac;
global using TranqService.Common.Extensions;
global using System.Net.Http;
global using TranqService.Shared.DataAccess;
global using TranqService.Ytdlp.DataAccess;
global using TranqService.Common.Attributes;
global using static TranqService.Common.Attributes.DependencyScopeAttribute;