name: Build, test and deploy

on:
  push:
    branches:
    - action-tests

jobs:
  deploy:
    # tests expect windows because of yt-dlp (for now)
    # Wix vs project also only compiles on windows (or so i've heard)
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore TranqService.sln
      
    - name: Build
      run: dotnet build --no-restore TranqService.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal TranqService.sln

    - name: Create Deployable builds
      run: |
        mkdir -p ${{ github.workspace }}/deployer/upload
        dotnet publish TranqService/TranqService.csproj --os=win -c Release -o ./deployer/builds/tranqservice-service-windows-latest
        dotnet publish TranqService.UI/TranqService.UI.csproj --os=win -c Release -o ./deployer/builds/tranqservice-ui-windows-latest
      
    - name: Zip Service (Windows)
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        directory: 'deployer/builds/tranqservice-service-windows-latest'
        filename: ${{ github.workspace }}/deployer/upload/service-windows-latest.zip

    - name: Zip UI (Windows)
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        directory: 'deployer/builds/tranqservice-ui-windows-latest'
        filename: '${{ github.workspace }}/deployer/upload/ui-windows-latest.zip'
        
    - name: Upload Service to S3 (Windows)
      uses: stcalica/s3-upload@0.0.1
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: 'eu-central-1'
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        package: 'deployer/upload/service-windows-latest.zip'

    - name: Upload UI to S3 (Windows)
      uses: stcalica/s3-upload@0.0.1
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: 'eu-central-1'
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        package: '${{ github.workspace }}/deployer/upload/ui-windows-latest.zip'