name: Build, test and deploy

on:
  push:
    branches:
    - action-tests

jobs:
  deploy:
    # tests expect windows because of yt-dlp (for now)
    # Wix vs project also only compiles on windows (or so i've heard)
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore TranqService.sln
      
    - name: Build
      run: dotnet build --no-restore TranqService.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal TranqService.sln

    - name: Create Deployable builds
      run: |
        mkdir -p ${{ github.workspace }}/deployer/upload
        dotnet publish TranqService/TranqService.csproj --os=win -c Release -o ./deployer/builds/tranqservice-service-windows-latest
        dotnet publish TranqService.UI/TranqService.UI.csproj --os=win -c Release -o ./deployer/builds/tranqservice-ui-windows-latest

    - name: Upload ZIP to S3 (Service - Windows)
      uses: NotCoffee418/s3-zip-upload@v1
      env:
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: eu-central-1
        SOURCE_MODE: ZIP
        SOURCE_PATH: ./deployer/builds/tranqservice-service-windows-latest
        DEST_FILE: service-windows-latest.zip

    - name: Upload ZIP to S3 (UI - Windows)
      uses: NotCoffee418/s3-zip-upload@v1
      env:
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: eu-central-1
        SOURCE_MODE: ZIP
        SOURCE_PATH: ./deployer/builds/tranqservice-ui-windows-latest
        DEST_FILE: ui-windows-latest.zip