name: Build, test and deploy

on:
  push:
    branches:
    - main

jobs:
  test:
    # tests expect windows because of yt-dlp (for now)
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore TranqService.sln
      
    - name: Build
      run: dotnet build --no-restore TranqService.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal TranqService.sln

  deploy:
    # deploy expect linux because of s3-sync-action
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore TranqService.sln
      
    - name: Build
      run: dotnet build --no-restore TranqService.sln
      
    - name: Create Deployable builds
      run: |
        mkdir -p ${{ github.workspace }}/deployer/upload
        dotnet publish TranqService/TranqService.csproj --os=win -c Release -o ./deployer/builds/tranqservice-service-windows-latest
        dotnet publish TranqService.UI/TranqService.UI.csproj --os=win -c Release -o ./deployer/builds/tranqservice-ui-windows-latest
      
    - name: Zip Service (Windows)
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        directory: 'deployer/builds/tranqservice-service-windows-latest'
        filename: ${{ github.workspace }}/deployer/upload/service-windows-latest.zip

    - name: Zip UI (Windows)
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        directory: './deployer/builds/tranqservice-ui-windows-latest'
        filename: '${{ github.workspace }}/deployer/upload/ui-windows-latest.zip'
        
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1 
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'               # optional: defaults to us-east-1
        SOURCE_DIR: '${{ github.workspace }}/deployer/upload/'      # optional: defaults to entire repository